name: "Get & Cache NPM Dependencies"
description: "Get & Cache Dependencies(via npm) for faster builds"
# Podemos definir los parámetros de entrada que queramos, en este caso el directorio de trabajo de manera opcional
inputs:
  working-dir:
    description: "The base directory to run the actions"
    required: false
    default: "."
runs:
  using: "composite"
  steps:
    - name: "Cache Dependencies"
      uses: "actions/cache@v4"
      id: cache-node-modules
      with:
        path: "${{ inputs.working-dir }}/node_modules"
        key: deps-node-modules-${{ hashFiles('${{ inputs.working-dir }}/package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
      # El tipo de shell que vamos a utilizar es obligatorio en composite actions
      shell: bash
